### ISSUE TITLE
Handle secondary errors on evaluating lazy seqs

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/babel-legacy#100]
Evaluating a lazy sequence in a :print-eval-result phase may lead to errors. The `-or-lazy` specs are designed to prevent this. However, we may need to deal with specs that don't have `or-lazy` conditions.  Need to make sure those are handled in a reasonable way and the stacktrace is reasonable. 
An example that came up at this point is 
```
(even? (map #(/ 9 %) [9 0]))
```
Fixing the spec on `even?` would make this specific case go away, but we need to make sure that it works third party code as well. 

It breaks in `d/type-and-val` on the line
```
(instance? clojure.lang.LazySeq s) ["a sequence " (print-str s)]
```
We may need to surround `print-str` with a try/catch processing block or some such.

**Comment by elenam** [comment]
Another example:
```
(defn f [x] (lazy-seq (conj (even? x 7) [9 8]))) 
(let [z (f 6)] (conj 6 z))
```
Here a spec error happens during the :print-eval-result phase in out call to `print-str`.

**Comment by stanislowskij** [comment]
This now corresponds to https://github.com/Clojure-Intro-Course/babel/issues/29 in the migration repository.
