### ISSUE TITLE
Fix overspeccing `int`

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/babel-legacy#104]
Our spec for `int` breaks compilation of specter :-( Not sure what the right spec should be, but it's more than `char?` or `number?`
Commented it out at this point.

**Comment by elenam** [comment]
The .edn error report indicates that the value is `(1)`:
```
   :clojure.spec.alpha/value (1)
```
It's unclear why a sequence is passed to `int`: it doesn't work on sequences.

**Comment by stanislowskij** [comment]
This now corresponds to https://github.com/Clojure-Intro-Course/babel/issues/32 in the migration repository.
