### ISSUE TITLE
Limit the number of the same lines printed in stacktrace

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/babel-legacy#110]
Stackoverflow can create a very long stacktrace, need to trim after filtering if it's too long.

- [ ] Set up a variable for max stacktrace
- [ ] Remove duplicates of anything that appears in the first n
- [ ] Add some indication that some elements were removed

**Comment by elenam** [comment]
So far just trimmed it blindly at 20.

**Comment by stanislowskij** [comment]
This now corresponds to https://github.com/Clojure-Intro-Course/babel/issues/35 in the migration repository.
