### ISSUE TITLE
Make "too many arguments to..." ("too few") syntax error more specific

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/babel-legacy#111]
Make special cases for `def`, `if`, what else?

**Comment by elenam** [comment]
This is valid: 
```
(def a "hi" 0)
```
This is not:
```
babel.middleware=> (def a 8 0)
Too many arguments to def.
```

**Comment by elenam** [comment]
Also has an error on special forms like `throw`:
```
babel.middleware=> (throw 3 4)
Too many arguments to throw,.
```
The actual message is:
```
:message "Too many arguments to throw, throw expects a single Throwable instance"
```
We might want to handle this wording in a general way, in addition to the specific wording for `throw`.

**Comment by stanislowskij** [comment]
This now corresponds to https://github.com/Clojure-Intro-Course/babel/issues/36 in the migration repository.
