### ISSUE TITLE
Print nested args in babel (and other non-macro?) spec errors 

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/babel-legacy#126]
```
babel.middleware=> (even? [(StringBuilder. "a")])
The first argument of (even? [#object[java.lang.StringBuilder 0x3ccd99fd "a"]]) was expected to be a number but is a vector [#object[java.lang.StringBuilder 0x3ccd99fd "a"]] instead.
....
babel.middleware=> (even? (StringBuilder. "a"))
The first argument of (even? "a") was expected to be a number but is a string "a" instead.
```

**Comment by elenam** [comment]
Need to check for collapsing ranges in nested expressions.

**Comment by elenam** [comment]
We need to move collapsing ranges into type-and-val. The current collapsing doesn't work because range-collapse gets a string, not a collection.

**Comment by elenam** [comment]
Done with babel spec messages, need to handle other spec messages.

**Comment by elenam** [comment]
I checked by setting up my own function and speccing it. Args are printed correctly. Haven't added this to tests since I'd like to use a more systematic approach to third-party spec testing. 
I am creating a separate issue for testing for third-party specs. 
This issues is closed.

**Comment by elenam** [comment]
Turns out it third party type specs that use `clojure.core` predicates were treated as babel specs, so we don't know if the args are actually printed correctly for third party specs.

**Comment by stanislowskij** [comment]
This now corresponds to https://github.com/Clojure-Intro-Course/babel/issues/42 in the migration repository.
