### ISSUE TITLE
Poor colorblind mode

### ISSUE THREAD

**Issue by BananaObserved** [Clojure-Intro-Course/babel-legacy#141]
The current colorblind setting changes the green to orange and lightens the red.  This makes the text harder, not easier, for me to read with my red-green colorblindness; the text is still clearly readable, but the contrast between the two sections is lower, which leads to the page seeming more like a wall of text.

**Comment by stanislowskij** [comment]
This now corresponds to https://github.com/Clojure-Intro-Course/babel/issues/51 in the migration repository.
