### ISSUE TITLE
The clojure.string/trim-newline doesn't work for part of the code.

### ISSUE THREAD

**Issue by plumstyle** [Clojure-Intro-Course/babel-legacy#26]
In the loggings/html-log.clj, I have couple functions that use clojure.string/trim-newline to trim down "\n". However, they only work for my modified error messages, but they don't work for my original error messages. This is now a big issue, so don't really worry about it. If anyone knows how to fix it I would be thankful.

**Comment by elenam** [comment]
I would prefer not to trim newlines for logging: it's helpful for debugging to know exactly what's in the error message.

**Comment by plumstyle** [comment]
cbb63f578b4519cbad0be1457d4a7e4eec9f7c88

**Comment by plumstyle** [comment]
Sure, it is fixed now at 6fdaef0008e48c9b2e98e8c997d70016b7d766cb.
