### ISSUE TITLE
 (int "9") misleading error message 

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/babel-legacy#47]
```Expected a character, but a string was given instead.``` 
Should say "character or number". May have to change this as a special case.

**Comment by elenam** [comment]
Add spec for it?

**Comment by JoshuaHamann** [comment]
I tried spec this, but this must be inline? not sure how to fix that issue

**Comment by elenam** [comment]
It's not inlined, but it might require a special case.  Let's not worry about this now.  I am keeping the issue open to see if any similar functions come up, and then we can handle all of them at once., hopefully.

**Comment by elenam** [comment]
I tried `long`, `short`, and `char`, all expect a number. Must be just `int`. Might need a spec (and then presumably for `char` as well since they probably would be used in tandem).

**Comment by elenam** [comment]
```
babel.middleware=> (int 6 7)
Syntax error (ArityException) compiling int at (C:\Users\E\AppData\Local\Temp\form-init1394949954368171726.clj:1:1).
Wrong number of args (2) passed to: clojure.core/int--inliner--5524
```
`int` is inlined. Subsumed by Clojure-Intro-Course/babel#1 .
